language: ruby
cache: bundler
rvm:
  - 2.2.0

env:
  - DB=sqlite
#  - DB=mysql
#  - DB=postgresql

before_script:
  - sudo apt-get install graphicsmagick
#  - mysql -e 'create database chromotype_test'
  - psql -c 'create database chromotype_test' -U postgres

#script:
#  - GEONAMES_USER=chromotype_ci RAILS_ENV=test bundle exec rake --trace db:migrate test:all
#  - ruby Test.rb

